# vim:ft=kitty
## name: Carbonfox
## author: EdenEast
## license: MIT
## upstream: https://github.com/EdenEast/nightfox.nvim/blob/main/extra/carbonfox/kitty.conf
## blurb: Carbonfox theme from the neovim colorscheme nightfox.nvim.

#: All the settings below are colors, which you can choose to modify, or use the
#: defaults. You can also add non-color based settings if needed but note that
#: these will not work with using kitty @ set-colors with this theme. For a
#: reference on what these settings do see https://sw.kovidgoyal.net/kitty/conf/

#: The basic colors

foreground                      #ededed
background                      #111111
selection_foreground            #ededed
selection_background            #212121


#: Cursor colors

cursor                          #06fc99
cursor_text_color               #111111


#: URL underline color when hovering with mouse

url_color                       #06fc99


#: kitty window border colors and terminal bell colors

active_border_color             #06fc99
inactive_border_color           #363636
bell_border_color               #fbbf24
# visual_bell_color               none


#: OS Window titlebar colors

# wayland_titlebar_color          system
# macos_titlebar_color            system


#: Tab bar colors

active_tab_foreground           #ededed
active_tab_background           #212121
inactive_tab_foreground         #525252
inactive_tab_background         #191919
# tab_bar_background              none
# tab_bar_margin_color            none


#: Colors for marks (marked text in the terminal)

# mark1_foreground black
# mark1_background #98d3cb
# mark2_foreground black
# mark2_background #f2dcd3
# mark3_foreground black
# mark3_background #f274bc


#: The basic 16 colors

#: black
color0 #191919
color8 #363636

#: red
color1 #f87171
color9 #f87171

#: green
color2  #06fc99
color10 #06fc99

#: yellow
color3  #fbbf24
color11 #fbbf24

#: blue
color4  #60a5fa
color12 #60a5fa

#: magenta
color5  #be95ff
color13 #c8a5ff

#: cyan
color6  #33b1ff
color14 #52bdff

#: white
color7  #b8b8b8
color15 #ededed


#: You can set the remaining 240 colors as color16 to color255.

color16 #3ddbd9
color17 #ff7eb6
